services:
  - type: web
    name: insodocs-landing
    runtime: node
    branch: main
    buildCommand: ""
    startCommand: npm start
    envVars:
      - key: STATIC_ROOT
        value: landing-site
      - key: AIRTABLE_BASE_ID
        value: appeTRS3rtFqXPJHY
      - key: AIRTABLE_WAITLIST_TABLE_ID
        value: tblqOjPaEku06GHA7
      - key: ALLOWED_ORIGIN
        value: https://insodocs.app
      - key: AIRTABLE_API_KEY
        sync: false
    pullRequestPreviewsEnabled: false
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
